pub fn normalize_legacy_action(action: &str) -> &str {
    match action {
        "EVENT_CREATED" => "TIMELINE_EVENT_CREATED",
        "EVENT_UPDATED" => "TIMELINE_EVENT_UPDATED",
        "EVENT_DELETED" => "TIMELINE_EVENT_DELETED",
        "EVENT_REPORT_FLAG_CHANGED" => "TIMELINE_EVENT_REPORT_INCLUDE_CHANGED",
        "EVENT_REPORT_INCLUDE_CHANGED" => "TIMELINE_EVENT_REPORT_INCLUDE_CHANGED",

        "CREATE_USER" => "USER_CREATED",
        "UPDATE_USER" => "USER_UPDATED",
        "BLOCK_USER" => "USER_BLOCKED",
        "UNBLOCK_USER" => "USER_UNBLOCKED",
        "RESET_USER_PASSWORD" => "USER_PASSWORD_RESET",
        "CHANGE_OWN_PASSWORD" => "USER_PASSWORD_CHANGED",

        "EXPORT_AUDIT_LOG" => "AUDIT_LOG_EXPORTED",

        _ => action,
    }
}
