#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProtectedOperation {
    CaseCreate,
    CaseRead,
    CaseUpdate,
    MaterialImport,
    MaterialRead,
    MaterialUpdate,
    ObjectCreate,
    ObjectRead,
    ObjectUpdate,
    RelationCreate,
    RelationRead,
    RelationUpdate,
    TimelineCreate,
    TimelineRead,
    TimelineUpdate,
    ReportDraftGenerate,
    ReportDraftRead,
    ReportDraftUpdate,
    DocxExport,
    AuditLogRead,
    UserManage,
    SettingsRead,
    SettingsUpdate,
    BackupRead,
    BackupCreate,
    BackupVerify,
    BackupRestore,
    IntegrityCheckRead,
    IntegrityCheckRun,
}

impl ProtectedOperation {
    pub fn action_name(self) -> &'static str {
        match self {
            Self::CaseCreate => "case.create",
            Self::CaseRead => "case.read",
            Self::CaseUpdate => "case.update",
            Self::MaterialImport => "material.import",
            Self::MaterialRead => "material.read",
            Self::MaterialUpdate => "material.update",
            Self::ObjectCreate => "object.create",
            Self::ObjectRead => "object.read",
            Self::ObjectUpdate => "object.update",
            Self::RelationCreate => "relation.create",
            Self::RelationRead => "relation.read",
            Self::RelationUpdate => "relation.update",
            Self::TimelineCreate => "timeline.create",
            Self::TimelineRead => "timeline.read",
            Self::TimelineUpdate => "timeline.update",
            Self::ReportDraftGenerate => "report.generate",
            Self::ReportDraftRead => "report.read",
            Self::ReportDraftUpdate => "report.update",
            Self::DocxExport => "docx.export",
            Self::AuditLogRead => "audit.read",
            Self::UserManage => "user.manage",
            Self::SettingsRead => "settings.read",
            Self::SettingsUpdate => "settings.update",
            Self::BackupRead => "backup.read",
            Self::BackupCreate => "backup.create",
            Self::BackupVerify => "backup.verify",
            Self::BackupRestore => "backup.restore",
            Self::IntegrityCheckRead => "integrity.read",
            Self::IntegrityCheckRun => "integrity.run",
        }
    }

    pub const fn all() -> &'static [Self] {
        &[
            Self::CaseCreate,
            Self::CaseRead,
            Self::CaseUpdate,
            Self::MaterialImport,
            Self::MaterialRead,
            Self::MaterialUpdate,
            Self::ObjectCreate,
            Self::ObjectRead,
            Self::ObjectUpdate,
            Self::RelationCreate,
            Self::RelationRead,
            Self::RelationUpdate,
            Self::TimelineCreate,
            Self::TimelineRead,
            Self::TimelineUpdate,
            Self::ReportDraftGenerate,
            Self::ReportDraftRead,
            Self::ReportDraftUpdate,
            Self::DocxExport,
            Self::AuditLogRead,
            Self::UserManage,
            Self::SettingsRead,
            Self::SettingsUpdate,
            Self::BackupRead,
            Self::BackupCreate,
            Self::BackupVerify,
            Self::BackupRestore,
            Self::IntegrityCheckRead,
            Self::IntegrityCheckRun,
        ]
    }
}
