// Thin re-export. All key constants now live in settings_catalog.
// This file is kept for backwards compatibility with existing use-sites.
pub use crate::models::settings_catalog::{
    KEY_ACCESS_ANALYST_CAN_CREATE_BACKUP, KEY_ACCESS_VIEWER_CAN_EXPORT_DOCX,
    KEY_BACKUP_DEFAULT_DIR, KEY_BACKUP_SAFETY_BEFORE_RESTORE, KEY_BACKUP_VERIFY_AFTER_CREATE,
    KEY_DOCX_DEFAULT_EXPORT_DIR, KEY_DOCX_DEFAULT_TEMPLATE, KEY_DOCX_INCLUDE_MATERIALS_TABLE,
    KEY_DOCX_INCLUDE_SHA256_TABLE, KEY_INTEGRITY_WARN_BEFORE_BACKUP,
    KEY_INTEGRITY_WARN_BEFORE_DOCX,
};
